language: java
jdk: openjdk14
sudo: false
env:
  - TEST_ITERATIONS=100
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Dgpg.skip=true
script:
  - mvn clean package -Dgpg.skip=true

